/**
 * Error codes for centralized error handling
 * Format: {CATEGORY}_{SPECIFIC_ERROR}
 * Categories: BLE, DEVICE, NETWORK, API, VALIDATION, STORAGE
 */

export const ERROR_CODES = {
  // Bluetooth BLE Errors
  BLE_NOT_ENABLED: "BLE_NOT_ENABLED",
  BLE_PERMISSION_DENIED: "BLE_PERMISSION_DENIED",
  BLE_LOCATION_PERMISSION_DENIED: "BLE_LOCATION_PERMISSION_DENIED",
  BLE_DEVICE_NOT_FOUND: "BLE_DEVICE_NOT_FOUND",
  BLE_CONNECTION_FAILED: "BLE_CONNECTION_FAILED",
  BLE_PAIRING_FAILED: "BLE_PAIRING_FAILED",
  BLE_DISCONNECTED: "BLE_DISCONNECTED",
  BLE_CHARACTERISTIC_NOT_FOUND: "BLE_CHARACTERISTIC_NOT_FOUND",
  BLE_WRITE_FAILED: "BLE_WRITE_FAILED",
  BLE_READ_FAILED: "BLE_READ_FAILED",

  // Device Errors
  DEVICE_NOT_FOUND: "DEVICE_NOT_FOUND",
  DEVICE_NOT_REGISTERED: "DEVICE_NOT_REGISTERED",
  DEVICE_REGISTRATION_FAILED: "DEVICE_REGISTRATION_FAILED",
  DEVICE_OFFLINE: "DEVICE_OFFLINE",
  DEVICE_KEY_INVALID: "DEVICE_KEY_INVALID",
  DEVICE_CONFIG_FAILED: "DEVICE_CONFIG_FAILED",

  // Network Errors
  NETWORK_UNAVAILABLE: "NETWORK_UNAVAILABLE",
  NETWORK_TIMEOUT: "NETWORK_TIMEOUT",
  WIFI_CONNECTION_FAILED: "WIFI_CONNECTION_FAILED",
  WIFI_INVALID_CREDENTIALS: "WIFI_INVALID_CREDENTIALS",
  WIFI_NETWORK_NOT_FOUND: "WIFI_NETWORK_NOT_FOUND",

  // API Errors
  API_UNAVAILABLE: "API_UNAVAILABLE",
  API_RATE_LIMIT_EXCEEDED: "API_RATE_LIMIT_EXCEEDED",
  API_AUTHENTICATION_FAILED: "API_AUTHENTICATION_FAILED",
  API_INVALID_RESPONSE: "API_INVALID_RESPONSE",
  SUPABASE_CONNECTION_FAILED: "SUPABASE_CONNECTION_FAILED",

  // Validation Errors
  VALIDATION_FAILED: "VALIDATION_FAILED",
  INVALID_INPUT: "INVALID_INPUT",
  MISSING_REQUIRED_FIELD: "MISSING_REQUIRED_FIELD",

  // Storage Errors
  STORAGE_READ_FAILED: "STORAGE_READ_FAILED",
  STORAGE_WRITE_FAILED: "STORAGE_WRITE_FAILED",
  STORAGE_DELETE_FAILED: "STORAGE_DELETE_FAILED",

  // Unknown Errors
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
